pop_deb = [
	"vscode",
	"barrier",

]

dot_deb = [
]

flatpak = [
	"steam",
	"dbeaver",
]
        

[[other]]
name = "Caskaydia Cove NF"
steps = [
	"dowload from Nerd Font",
"extracted",
	"copied to ~/.local/share/fonts",
	"executed fc-cache -f -v",
]

todo = [
	"discord",
	"wezterm",
	"neovim",
	"bob",
	"kitty",
	"zoxide",
	"starship",
	"bat",
	"eza",
	"fd",
	"fzf",
	"ripgrep",
	"gitui",
	"yazi",
]
